### PR TITLE
fix: add tool instances information before destroy

### PR DESCRIPTION
**Pull request by wzymumon**
# Summary

bugfix & logs improvement

## Description

Describe tool instances information before exec destroy command

### Related Issues

https://github.com/devstream-io/devstream/issues/429

### Current Behavior

```shell
$ ./dtm destroy
2022-04-21 23:05:48 ℹ [INFO]  Destroy started.
Continue? [y/n]
Enter a value (Default is n): y

2022-04-21 23:05:50 ℹ [INFO]  Start executing the plan.
2022-04-21 23:05:50 ℹ [INFO]  Changes count: 1.
2022-04-21 23:05:50 ℹ [INFO]  -------------------- [  Processing progress: 1/1.  ] --------------------
2022-04-21 23:05:50 ℹ [INFO]  Processing: vault (vault) -> Delete ...
2022-04-21 23:05:51 ℹ [INFO]  Uninstalling openldap helm chart.
2022-04-21 23:05:51 ⚠ [WARN]  Release is not found, maybe it has been deleted.
```

### New Behavior

```shell
ubuntu@VM-12-5-ubuntu:~/dtmtest$ ./dtm destroy -f config.yaml
2022-05-13 10:21:33 ℹ [INFO]  Destroy started.
2022-05-13 10:21:33 ℹ [INFO]  Tool (githubactions-golang/default) will be deleted.
2022-05-13 10:21:33 ℹ [INFO]  Tool (github-repo-scaffolding-golang/default) will be deleted.
Continue? [y/n]
Enter a value (Default is n): y

2022-05-13 10:21:37 ℹ [INFO]  Start executing the plan.
2022-05-13 10:21:37 ℹ [INFO]  Changes count: 2.
2022-05-13 10:21:37 ℹ [INFO]  -------------------- [  Processing progress: 1/2.  ] --------------------
2022-05-13 10:21:37 ℹ [INFO]  Processing: (githubactions-golang/default) -> Delete ...
2022-05-13 10:21:37 ℹ [INFO]  Deleting GitHub Actions workflow pr-builder.yml ...
2022-05-13 10:21:38 ✔ [SUCCESS]  GitHub Actions workflow pr-builder.yml removed.
2022-05-13 10:21:38 ℹ [INFO]  Deleting GitHub Actions workflow main-builder.yml ...
2022-05-13 10:21:38 ✔ [SUCCESS]  GitHub Actions workflow main-builder.yml removed.
2022-05-13 10:21:38 ℹ [INFO]  Prepare to delete 'githubactions-golang_default' from States.
2022-05-13 10:21:38 ✔ [SUCCESS]  Tool (githubactions-golang/default) delete done.
2022-05-13 10:21:38 ℹ [INFO]  -------------------- [  Processing progress: 2/2.  ] --------------------
2022-05-13 10:21:38 ℹ [INFO]  Processing: (github-repo-scaffolding-golang/default) -> Delete ...
2022-05-13 10:21:39 ✔ [SUCCESS]  GitHub repo go-webapp-devstream-demo removed.
2022-05-13 10:21:39 ℹ [INFO]  Prepare to delete 'github-repo-scaffolding-golang_default' from States.
2022-05-13 10:21:39 ✔ [SUCCESS]  Tool (github-repo-scaffolding-golang/default) delete done.
2022-05-13 10:21:39 ℹ [INFO]  -------------------- [  Processing done.  ] --------------------
2022-05-13 10:21:39 ✔ [SUCCESS]  All plugins destroyed successfully.
2022-05-13 10:21:39 ✔ [SUCCESS]  Destroy finished.
```

### Screenshots

image

### CODE REVIEW

**Comment by IronCore864** [comment]
@wzymumon thanks for the contribution!

Just one question before merging: is `dtm destroy` (besides `dtm delete`) also tested?

**Comment by wzymumon** [comment]
> 
@IronCore864  Sorry, there are some problems with my description, it has been updated.

**Comment by IronCore864** [comment]
Thanks a lot for this quality-of-life improvement. Kudos to @wzymumon

**Review by IronCore864 — APPROVED** [review]

**Comment by IronCore864** [comment]
Closes #429

**Pull request merged**
