### PR TITLE
Docs(Translation): Commit Messages - Chinese Version #709

### PR DESCRIPTION
**Pull request by aucker**
Signed-off-by: aucker <aucker@qq.com>
## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [ ] I have added relevant tests

## Description

This PR translate the docs `commit-messages.md` into Chinese.

## Related Issues

This PR is related to this [issue](https://github.com/devstream-io/devstream/issues/709)

Closes https://github.com/devstream-io/devstream/issues/709.

## New Behavior (screenshots if needed)

The Chinese version of `commit-messages.md`.
image

### CODE REVIEW

**Comment by daniel-hutao** [comment]
Why did you close it?

**Comment by aucker** [comment]
Sorry, I failed the DCO, I don't know the how to add the sign message. Should I reopen this PR or recommit again?

**Comment by aucker** [comment]
> Why did you close it?
Sorry, I failed the DCO, I don't know the how to add the sign message. Should I reopen this PR or recommit again?

**Comment by daniel-hutao** [comment]
> Why did you close it?
> Sorry, I failed the DCO, I don't know the how to add the sign message. Should I reopen this PR or recommit again?

https://github.com/devstream-io/devstream/pull/700#issuecomment-1160235374 @aucker

**Comment by IronCore864** [comment]
@aucker A kind reminder that you haven't signed off on your commit(s) yet.

Licensing is important to open source projects. It provides some assurances that the software will continue to be available based on the terms that the author(s) desired. So, we require that contributors sign off on commits submitted to our project's repositories.
The [Developer Certificate of Origin (DCO)](https://developercertificate.org/) is a way to certify that you wrote and have the right to contribute the code you are submitting to the project.

To learn how to do this, check out our [official doc here](https://docs.devstream.io/en/latest/contributing_guide/#sign-your-commits).

**Comment by IronCore864** [comment]
> 我认为conventional commits或许可以不用翻译成“传统的提交”，因为这基本上是一个专有名词了，指代一系列的提交信息的编写规范。如果翻译成“传统的提交”，可能中文用户反而不理解是什么了；对于不认识英文的，用户知道这是个自己不知道的东西，点开看看翻译一下就知道了？ @aucker

我先直接在这个PR里修改了哈，见谅。

**Comment by IronCore864** [comment]
Hi @aucker 

Thanks for your contribution! We will test your change locally and try to merge it as soon as possible.

Please join our [Slack here](https://join.slack.com/t/devstream-io/shared_invite/zt-16tb0iwzr-krcFGYRN7~Vv1suGZjdv4w). Feel free to reach out and request to join the [contributor channel](https://devstream-io.slack.com/messages/contributors)! We are also in CNCF now; please also consider joining [this channel in CNCF Slack](https://cloud-native.slack.com/messages/devstream).

In the meantime, feel free to check out our [new contributor guide](https://docs.devstream.io/en/latest/contributing_guide/#new-contributor-guide). We have quite a few pieces of documentation explaining the basic concepts and how to work on DevStream. Read them in the ["Developer Guide"](https://docs.devstream.io/en/latest/development/development-workflow/) section of the documentation.

If you are searching for something else to work on, please do check out the ["find an issue"](https://docs.devstream.io/en/latest/contributing_guide/#find-an-issue) section. The ["help wanted"](https://github.com/devstream-io/devstream/labels/help%20wanted) label is an excellent place to continue. If you are not completely confident yet, maybe you can warm yourself up by solving another ["good first issue"](https://docs.devstream.io/en/latest/development/good-first-issues/).

Tiexin

**Comment by IronCore864** [comment]
Closes https://github.com/devstream-io/devstream/issues/709

**Review by IronCore864 — APPROVED** [review]

**Pull request merged**
