### PR TITLE
feat: add editorconfig

### LINKED ISSUE #629: :four_leaf_clover: `Proposal`: editorconfig
## What Would You Like to Add? Why is This Needed?

Add .editorconfig to add new line at eof automatically. @iyear's original idea.

Refer to: https://stackoverflow.com/a/41127396.

### PR DESCRIPTION
**Pull request by iyear**
## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](../CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [x] I have added relevant tests

## Description
add `.editorconfig` to add new line at eof automatically.

https://stackoverflow.com/a/41127396

Closes #629

### CODE REVIEW

**Review by daniel-hutao — APPROVED** [review]
/lgtm
Please take a review at this pr @IronCore864

**Comment by iyear** [comment]
`Goland` supports the `editorconfig` feature. But `vsc` requires a plugin to be installed to support it. But it's better than nothing.

https://www.jetbrains.com/help/go/configuring-code-style.html#editorconfig

**Comment by algobot76** [comment]
We could set more options to the `.editorconfig` file, see: https://github.com/kubernetes/dashboard/blob/master/.editorconfig

**Review by IronCore864 — APPROVED** [review]

**Comment by IronCore864** [comment]
> We could set more options to the `.editorconfig` file, see: https://github.com/kubernetes/dashboard/blob/master/.editorconfig

Great suggestion. Let me copy-paste that XD

**Comment by IronCore864** [comment]
Thanks @iyear for the quality-of-life improvement idea and thanks @algobot76 for contributing more to it.

**Comment by IronCore864** [comment]
Closes https://github.com/devstream-io/devstream/issues/629.

**Pull request merged**
