### PR TITLE
docs: optmize nav

### PR DESCRIPTION
**Pull request by imxw**
Signed-off-by: xuwu <ixw1991@126.com>

## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [x] I have added relevant tests

## Description

- support wildcards and subdirectory nav config

For a more detailed introduction, please refer to https://oprypin.github.io/mkdocs-literate-nav/reference.html#nav-list-syntax

## Related Issues

Closes https://github.com/devstream-io/devstream/issues/722

N/A
## New Behavior (screenshots if needed)

image
image

### CODE REVIEW

**Review by daniel-hutao — APPROVED** [review]

**Comment by daniel-hutao** [comment]
Great! Works perfectly!

**Comment by IronCore864** [comment]
Fantastic work. Could you please also update this doc: https://github.com/devstream-io/devstream/blob/main/docs/development/mkdocs.md.

**Comment by imxw** [comment]
> #708
> 
> > Fantastic work. Could you please also update this doc: https://github.com/devstream-io/devstream/blob/main/docs/development/mkdocs.md.
> 
> Chinese version will be available soon, @imxw please to pay attention to this.

ok

**Review by IronCore864 — APPROVED** [review]

**Comment by IronCore864** [comment]
Great work on the English doc. Thanks @imxw

**Pull request merged**
