### PR TITLE
fix: fix go plugin log error

### PR DESCRIPTION
**Pull request by aFlyBird0**
## Description
fix go plugin log error

## Related Issues
#502

### CODE REVIEW

**Comment by daniel-hutao** [comment]
I have a question about this change: how to test it?

image

@IronCore864 @aFlyBird0

**Comment by daniel-hutao** [comment]
@IronCore864 Should we delete the `main()`? I deleted it and don't saw any errors.

Maybe we can refactor all `main.go` with plugins like below:

```go
package main

import (
	"github.com/devstream-io/devstream/internal/pkg/plugin/argocd"
)

// NAME is the name of this DevStream plugin.
const NAME = "argocd"

// Plugin is the type used by DevStream core. It's a string.
type Plugin string

// DevStreamPlugin is the exported variable used by the DevStream core.
var DevStreamPlugin Plugin

// Create implements the create of ArgoCD.
func (p Plugin) Create(options map[string]interface{}) (map[string]interface{}, error) {
	return argocd.Create(options)
}

// Update implements the update of ArgoCD.
func (p Plugin) Update(options map[string]interface{}) (map[string]interface{}, error) {
	return argocd.Update(options)
}

// Delete implements the delete of ArgoCD.
func (p Plugin) Delete(options map[string]interface{}) (bool, error) {
	return argocd.Delete(options)
}

// Read implements the read of ArgoCD.
func (p Plugin) Read(options map[string]interface{}) (map[string]interface{}, error) {
	return argocd.Read(options)
}
```

**Comment by aFlyBird0** [comment]
> 

In fact, this main function will not be executed. But it's really wrong.

> from IronCore: we only have it there to shut the IDE warnings up

I guess it is used to avoid the waning of "unused var"?

**Comment by IronCore864** [comment]
golangci-lint would report an error if we deleted the main() func.

Also, my IDE (VSCode) would give an error because of lacking the main() func.

I suggest that we keep the main() func so that beginners have less questions when they just get started.

**Review by daniel-hutao — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
