### PR TITLE
docs: translation contributor ladder

### PR DESCRIPTION
**Pull request by JueShanCoder**
## Description
Add contributor ladder chinese doc.

### CODE REVIEW

**Comment by steinliber** [comment]
A kind reminder that you haven't signed off on your commit(s) yet. Check out our [official doc](https://docs.devstream.io/en/latest/contributing_guide/#sign-your-commits) to learn how to do this.

**Review by aFlyBird0 — APPROVED** [review]
你好，非常感谢你的贡献！因为是翻译 pr，我直接用中文了。

我看到了你有很多意译的地方，这非常赞！我也尽量保留了你意译的地方。比如“推荐官”。

有以下地方可以改进，注意一下就好，我已经帮你修复了。

1. 有许多句子漏翻了，下次可以仔细些。
2. 注意专有名词和普通名词（是否大写）的区别：`Contributor` 是特指贡献者这一最低级别，`contributor` 是泛指所有级别的贡献者。

**Comment by aFlyBird0** [comment]
Hi @JueShanCoder , thanks for your contribution! Please [join CNCF's Slack](https://slack.cncf.io), and join our [channel in CNCF Slack](https://cloud-native.slack.com/messages/devstream)!

Here are a few useful things for you to continue your open-source journey:

- If you are searching for something else to work on, please see ["find an issue"](https://docs.devstream.io/en/latest/contributing_guide/#find-an-issue).
- Check out our [new contributor guide](https://docs.devstream.io/en/latest/contributing_guide/#new-contributor-guide) and the ["Developer Guide"](https://docs.devstream.io/en/latest/development/development-workflow/).
- Read our [blog](https://blog.devstream.io/); they are on [Medium](https://medium.com/devstream), too.

We made changes to your PR directly so that your contribution can be merged quicker. We hope you don't mind!

**Comment by aFlyBird0** [comment]
A kind reminder that you haven't signed off on your commit(s) yet. Check out our [official doc](https://docs.devstream.io/en/latest/contributing_guide/#sign-your-commits) to learn how to do this. Also, DevStream community follows the [conventional commits specification](https://www.conventionalcommits.org/eXn/v1.0.0/). Please read our [doc](https://docs.devstream.io/en/latest/development/commit-messages/) and update your commit message.

**Comment by aFlyBird0** [comment]
@JueShanCoder 上面发了个 slack 的频道，这是我们主要的交流方式，请加一下。以及关于 commit message 和 DCO 的描述，也请查阅一下。

请在微信群加一下我，aFlyBird0，以发放证书等。:heart:

**Comment by aFlyBird0** [comment]
@IronCore864 

Please review. Remember to use `squash`, you can squash @JueShanCoder's PR into one commit, and remain my commit.

**Review by IronCore864 — APPROVED** [review]

**Comment by IronCore864** [comment]
有可能是截至目前质量最高的一篇文档PR，非常感谢！如果感兴趣，可以加入我们的contributor slack channel，后续我们也在准备一些数字奖章的发放，敬请关注：）

**Comment by IronCore864** [comment]
@JueShanCoder for future PRs, please remember to create an issue first, and assign it to yourself so that others know you are already working on it.

For doc translation-related issues, please discuss them with the community first. Thanks for your contribution!

**Pull request merged**
