### PR TITLE
feat: Improving The Robustness of Config File

### PR DESCRIPTION
**Pull request by byene0923**
## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [ ] I have added relevant tests

## Description
Improving The Robustness of Config File
- judge core config by key `core`
- judge tool config by key `tools`

## Related Issues
https://github.com/devstream-io/devstream/issues/659

### CODE REVIEW

**Comment by IronCore864** [comment]
Hi @byene0923, thanks for your contribution! Please [join CNCF's Slack](https://slack.cncf.io), and join our [channel in CNCF Slack](https://cloud-native.slack.com/messages/devstream)!

Here are a few useful things for you to continue your open-source journey:

- If you are searching for something else to work on, please see ["find an issue"](https://docs.devstream.io/en/latest/contributing_guide/#find-an-issue).
- Check out our [new contributor guide](https://docs.devstream.io/en/latest/contributing_guide/#new-contributor-guide) and the ["Developer Guide"](https://docs.devstream.io/en/latest/development/development-workflow/).
- Read our [blog](https://blog.devstream.io/); they are on [Medium](https://medium.com/devstream), too.

We made changes to your PR directly so that your contribution can be merged quicker. We hope you don't mind!

In this PR, there are a few issues worth noting:

- spaces between Chinese and English: either have them all or not have a single one of them. The key is to be consistent.
- some English words or even sentences are not translated.
- spelling: we need to keep proper nouns consistent to their official names. I.E., Yaml V.S. YAML.

Please pay closer attention in your next PR:)

Also, **for translation documentations, you need to create an issue and discuss with our community first before working on it.**

**Comment by hxcGit** [comment]
Hi @byene0923 , thanks for your contribution! Please [join CNCF's Slack](https://slack.cncf.io), and join our [channel in CNCF Slack](https://cloud-native.slack.com/messages/devstream)!

Here are a few useful things for you to continue your open-source journey:

- If you are searching for something else to work on, please see ["find an issue"](https://docs.devstream.io/en/latest/contributing_guide/#find-an-issue).
- Check out our [new contributor guide](https://docs.devstream.io/en/latest/contributing_guide/#new-contributor-guide) and the ["Developer Guide"](https://docs.devstream.io/en/latest/development/development-workflow/).
- Read our [blog](https://blog.devstream.io/); they are on [Medium](https://medium.com/devstream), too.

And a kind reminder that you haven't signed off on your commit(s) yet. Check out our [official doc](https://docs.devstream.io/en/latest/contributing_guide/#sign-your-commits) to learn how to do this.

If you have any questions, I would be delighted to assist you!

**Comment by hxcGit** [comment]
Hi @byene0923 , thanks for your contribution! Please [join CNCF's Slack](https://slack.cncf.io), and join our [channel in CNCF Slack](https://cloud-native.slack.com/messages/devstream)!

Here are a few useful things for you to continue your open-source journey:

- If you are searching for something else to work on, please see ["find an issue"](https://docs.devstream.io/en/latest/contributing_guide/#find-an-issue).
- Check out our [new contributor guide](https://docs.devstream.io/en/latest/contributing_guide/#new-contributor-guide) and the ["Developer Guide"](https://docs.devstream.io/en/latest/development/development-workflow/).
- Read our [blog](https://blog.devstream.io/); they are on [Medium](https://medium.com/devstream), too.

A kind reminder that you haven't signed off on your commit(s) yet. Check out our [official doc](https://docs.devstream.io/en/latest/contributing_guide/#sign-your-commits) to learn how to do this. 

Also, DevStream community follows the [conventional commits specification](https://www.conventionalcommits.org/en/v1.0.0/). Please read our [doc](https://docs.devstream.io/en/latest/development/commit-messages/) and update your commit message.
- It seems that you shoud put a space after `feat:`.

**Comment by byene0923** [comment]
ohh, thanks a lot for your review. i fix it

**Review by aFlyBird0 — APPROVED** [review]
LGTM. Thank you for your contribution! 👏

**Pull request merged**
