### PR TITLE
fix: change flag "name" to "id" and add "all" flag

### PR DESCRIPTION
**Pull request by 24sama**
## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](../CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [x] I have added relevant tests

## Description

* Change flag "name" to "id".
* Add "all" flag to `dtm show status` command.

## Related Issues

#557

### CODE REVIEW

**Comment by daniel-hutao** [comment]
@24sama Hello Leo Li, I tested this pr locally and found some error(Warn):

`./dtm show status --all`                                                                                                         

```sh
2022-05-20 14:19:29 ⚠ [WARN]  Empty instance name. Maybe you forgot to add --id=INSTANCE_ID. The default value "default" will be used.
```

Here may be some improvement can be done.

**Comment by 24sama** [comment]
> What if the user doesn't enter any flags? I think --all defaults to true will be more appropriate
```
dtm show status -p xxxx 
```
It will return all results, which isn't our expected.
I think we only need to add a little logic. If the user doesn't enter any flags, we make the value of `--all` to `true`.

**Comment by daniel-hutao** [comment]
> Hi @daniel-hutao , thanks for your review.
> 
> > What if the user doesn't enter any flags? I think --all defaults to true will be more appropriate
> 
> ```
> dtm show status -p xxxx 
> ```
> 
> It will return all results if `--all` defaults to true, which isn't our expected. I think we only need to add a little logic. If the user doesn't enter any flags, we make the value of `--all` to `true`.
> 
> And I make some changes, PTAL.

Cool, your are right, the --all flag should be true only when no flags provided.

**Review by daniel-hutao — APPROVED** [review]
lgtm

**Pull request merged**
