### PR TITLE
chore: accurate code comments and minor code changes

### PR DESCRIPTION
**Pull request by aFlyBird0**
## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](../CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [ ] I have added relevant tests

## Description
1. accurate some code comments.
2. fix some log errors, spelling errors.
3. minor code changes.

### CODE REVIEW

**Comment by daniel-hutao** [comment]
@aFlyBird0 Please check the ci error.

**Comment by aFlyBird0** [comment]
> @aFlyBird0 Please check the ci error.

Sorry, new code has been committed. (I ran `go test ... locally before committing. /... `. But I forgot that I changed the code in the configloader via GitHub pilot, thinking it was a ci test like the last one.)

**Review by IronCore864 — APPROVED** [review]

**Comment by IronCore864** [comment]
Very detailed change by @aFlyBird0. Thanks very much. I committed a few grammar updates in the PR directly; hope you won't mind.

Please do a regression test (for example, the GitOps process) to make sure the code change didn't break anything.

**Comment by IronCore864** [comment]
@aFlyBird0 keep up the good work!

**Comment by aFlyBird0** [comment]
Thanks for your additional commits sincerely! I will do the  regression test this afternoon. @IronCore864

**Comment by daniel-hutao** [comment]
@aFlyBird0 @IronCore864 How about merge this pr now. I'll test it locally today. I'm also changing the logic of the package `configloader`, and this pr is actually in conflict with mine. I want to merge this pr to main and then merge it to my local branch, then I resolved the conflict and continued to develop, and then tested the related functions after I finished the development.

**Review by daniel-hutao — APPROVED** [review]

**Pull request merged**
