### PR TITLE
Fix logic for loadconf return value

### PR DESCRIPTION
**Pull request by linuxtmty**
###issues
https://github.com/devstream-io/devstream/issues/606

### CODE REVIEW

**Comment by daniel-hutao** [comment]
Please hang it up after #604 merged. See https://github.com/devstream-io/devstream/issues/606#issuecomment-1138076943 for more info.

**Comment by IronCore864** [comment]
@daniel-hutao @linuxtmty please follow up on this PR. Shall we close it, or?

**Comment by daniel-hutao** [comment]
> Please hang it up after #604 merged. See [#606 (comment)](https://github.com/devstream-io/devstream/issues/606#issuecomment-1138076943) for more info.

@IronCore864 I'm following it. I'll come back to see if close this pr after #604 finished.

**Comment by IronCore864** [comment]
@linuxtmty seems there are some conflicts. Please try and see if you can resolve them. Thanks!

**Pull request closed without merging**
