### PR TITLE
docs: update project-layout.zh.md

### LINKED ISSUE #711: :open_book: `Docs(Translation)`: Project Layout - Chinese Version
### What should be changed?

Now we have the document [Project Layout](https://github.com/devstream-io/devstream/blob/main/docs/development/project-layout.md), so the corresponding Chinese version can also start writing (translation) [here](https://github.com/devstream-io/devstream/blob/main/docs/development/project-layout.zh.md).

---

The translation does not need to correspond strictly to each sentence, it just needs to express the same meaning. "Meaningful translation" is recommended . Please feel free to ask me when you have any questions.

### PR DESCRIPTION
**Pull request by IZUMI-Zu**
Signed-off-by: BSS ZU <274620705z@gmail.com>

## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [X] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [X] My code has the necessary comments and documentation (if needed).
- [ ] I have added relevant tests

## Description

This PR translate the docs project-layout.zh.md into Chinese.

## Related Issues

close #711

### CODE REVIEW

**Comment by IronCore864** [comment]
@IZUMI-Zu 首先感谢您的翻译贡献。

用机器翻译软件搞出整体的雏形没有问题，但一定请进行人工的校对和审核，确保用词一致性、风格符合native speaker的习惯。

例：

> 存放私人程序和库的代码。这里是你不希望别人在其应用程序或库中导入的代码。请注意，这种布局模式是由 Go 编译器强制执行的。更多细节请参见 Go 1.4 [`release notes`](https://golang.org/doc/go1.4#internalpackages) 。请注意，你并不局限于顶层的`internal`目录。你可以在项目树的任何一级有一个以上的`internal`目录。

- 私人 - 私有
- 库-代码库 （lib一般是库，repo则是代码库，代码仓库，甚至不翻译）
- 布局模式 - 非常生硬。不如说是目录结构、代码组织结构等
- “你并不局限于xx目录” 不是一个语法上合规的中文句子，也不符合中文母语者的说话习惯


建议您在开始贡献之前，先阅读我们的[CONTRIBUTING](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md)文档，并在PR里打钩，let the community and the reviewers know that we are on the same page.

关于文档的修改是尤其重要的，因为这影响所有新用户、新贡献者的体验，请一定确保：
- 人工校对机器翻译结果
- 用词一致性
- 语言风格符合中国人的说话习惯

**Comment by aFlyBird0** [comment]
Hi @IZUMI-Zu , thanks for your contribution! Please [join CNCF's Slack](https://slack.cncf.io), and join our [channel in CNCF Slack](https://cloud-native.slack.com/messages/devstream)!
Here are a few useful things for you to continue your open-source journey:
- If you are searching for something else to work on, please see ["find an issue"](https://docs.devstream.io/en/latest/contributing_guide/#find-an-issue).
- Check out our [new contributor guide](https://docs.devstream.io/en/latest/contributing_guide/#new-contributor-guide) and the ["Developer Guide"](https://docs.devstream.io/en/latest/development/development-workflow/).
- Read our [blog](https://blog.devstream.io/); they are on [Medium](https://medium.com/devstream), too.


We made changes to your PR directly so that your contribution can be merged quicker. We hope you don't mind! ✊✊

**Review by aFlyBird0 — APPROVED** [review]

**Comment by aFlyBird0** [comment]
Thanks again for your contribution, and if you want to contribute document translations in the future, you can take a look at this document first. @IZUMI-Zu 🙌

[为DevStream创建中文文档](https://docs.devstream.io/en/latest/development/mkdocs.zh/)

**Comment by aFlyBird0** [comment]
@IronCore864 Could you please start a review? Thank you!

**Comment by daniel-hutao** [comment]
Hello @IZUMI-Zu, Please add my WeChat, I have a gift for you, and a certificate. You can find me at [Slack](https://cloud-native.slack.com/archives/C03LA2B8K0A) or [WeChat group](https://github.com/devstream-io/devstream/raw/main/docs/images/wechat-group-qr-code.png).

**Pull request merged**
