### PR TITLE
chore(refactor): refactor helm validate and set default timeout.

### PR DESCRIPTION
**Pull request by WyattJia**
## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [x] I have added relevant tests

### CODE REVIEW

**Comment by WyattJia** [comment]
Refer issue #786 ,@daniel-hutao please check and review my change, and thanks.

**Comment by aFlyBird0** [comment]
Hi @WyattJia , thanks for your contribution! Please [join CNCF's Slack](https://slack.cncf.io), and join our [channel in CNCF Slack](https://cloud-native.slack.com/messages/devstream)!
Here are a few useful things for you to continue your open-source journey:
- If you are searching for something else to work on, please see ["find an issue"](https://docs.devstream.io/en/latest/contributing_guide/#find-an-issue).
- Check out our [new contributor guide](https://docs.devstream.io/en/latest/contributing_guide/#new-contributor-guide) and the ["Developer Guide"](https://docs.devstream.io/en/latest/development/development-workflow/).
- Read our [blog](https://blog.devstream.io/); they are on [Medium](https://medium.com/devstream), too.

**Comment by aFlyBird0** [comment]
And I found that the commit message failed, here is the reason. Hope it could help you. ❤️  @WyattJia 

image

**Review by aFlyBird0 — APPROVED** [review]
LGTM. It meets the "single responsibility principle". Just go to resolve the CI failures.

**Review by daniel-hutao — APPROVED** [review]
lgtm

Please fix the doc & commit message error

**Comment by WyattJia** [comment]
@aFlyBird0 @daniel-hutao I've updated commite message and remove the "full stop", please help me check my change, very honored to participate in this contribution.

**Pull request merged**
