### PR TITLE
Fix duplicate downloads and refactor code

### LINKED ISSUE #818: :bomb: `Bug`: Duplicate downloads
### What Happened?

When using the `init` command, `dtm` checks for non-existent plugins and pulls them from the remote. However, I find that every time I use `init`, it triggers an md5 mismatch and re-downloads, even though the corresponding ones have all downloaded successfully.

I found that 

https://github.com/devstream-io/devstream/blob/1d2c60493cc5327849862dce7e8f075591b5f3ba/internal/pkg/pluginmanager/manager.go#L75-L78

There is an error in the logic of this section. Here the download has already finished, but the `StatError` used is still the one before the download, which will cause `pluginFileErr == nil && pluginMD5FileErr == nil` to never hold.

I add some debug outputs.

`log.Debug(isMD5Match, pluginFileErr, pluginMD5FileErr)`

image

This means that every time a user uses `init`, twice as much traffic is consumed.

### How to Reproduce?

`dtm init -f quickstart.yaml --debug`

### Anything else

I will change the logic of this function and try to fix it.

Please assign me.

### DevStream Version

latest

### PR DESCRIPTION
**Pull request by iyear**
## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [x] I have added relevant tests

## Description
1. fix duplicate downloads logic
2. make outputs more beautiful
3. refactor some code

## Related Issues
close #818 

## New Behavior (screenshots if needed)

The version in 3 screenshots is a forced change during testing, and the commits have been submitted in accordance with the normal.

### Download all plugins from remote
full

### Download some plugins from remote
part

### No need to download plugins from remote
none

### Init in dev version
image

### CODE REVIEW

**Review by IronCore864 — APPROVED** [review]

**Comment by IronCore864** [comment]
Very good refactor. Well done! @iyear

**Comment by IronCore864** [comment]
@hxcGit need another review here. Please have a local test if possible.

**Review by daniel-hutao — APPROVED** [review]
Good job!

**Comment by aFlyBird0** [comment]
It's very cool! @iyear 🚀

**Pull request merged**
