### PR TITLE
docs: fix some link errors 

### PR DESCRIPTION
**Pull request by huang12zheng**
## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](../CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [ ] I have added relevant tests

## Description
1. add md suffix and relative position for link
2.  modified CONTRIBUTING 's link in pull_request_template.md

## Related Issues
none

## New Behavior (screenshots if needed)
click link in github doc, would never 404
click link in https://www.devstream.io/ would never 404

### CODE REVIEW

**Review by IronCore864 — APPROVED** [review]
Thanks @huang12zheng for this detailed documentation improvement. I can't say enough how important non-code contribution is. For that, I'm truly grateful.

FYI: we are using `mkdocs` for documentation. You can run `mkdocs serve` locally to review your changes. We will create documentation on the usage of mkdocs to make it much easier for you to review your doc changes locally in real-time.

The links improvement in this PR also works for browsing them directly in GitHub. Good work. Thanks a lot.

**Comment by IronCore864** [comment]
Tested locally; merging now.

@huang12zheng the commit messages are a bit duplicated without too much information. In the future, I kindly suggest that you squash the commits into a single one to make it more clear with useful information. For example, see [this link](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git).

Thanks!

**Comment by IronCore864** [comment]
@huang12zheng we also try our best to follow a standard on commit messages, see it in detail [here](https://docs.devstream.io/en/latest/development/commit-messages/). Standard makes our daily routine much easier and quicker; I hope this won't cause you extra operational overhead.

**Comment by IronCore864** [comment]
@huang12zheng join our contributor's slack channel using this link if you haven't done so:

https://join.slack.com/t/devstream-io/shared_invite/zt-16tb0iwzr-krcFGYRN7~Vv1suGZjdv4w

**Comment by huang12zheng** [comment]
I'm still not familiar with git. 
thanks for you.  I didn't even realize you'd done git reset for me.
@IronCore864

**Comment by daniel-hutao** [comment]
image

There are at least 3 ways to write it that work correctly, and I find the third one the most concise and elegant.

**Comment by huang12zheng** [comment]
@daniel-hutao 
when you click on Github, it looks like maybe 404 if the third one.

**Comment by daniel-hutao** [comment]
> @daniel-hutao
> when you click on Github, it looks like maybe 404 if the third one.

Yeah, it does well with MkDocs but not recognizable by GitHub. Your modifications are great and I agree that this is the best options. @huang12zheng Great job!

But I believe we still need a place to document why we use this way to avoid more mistakes in the future. @IronCore864

**Comment by aFlyBird0** [comment]
> @daniel-hutao when you click on Github, it looks like maybe 404 if the third one.

Fantastic! You convinced me!

**Pull request merged**
