### PR TITLE
Proposal issue#571: check goimports' existance,  go on installing onl…

### PR DESCRIPTION
**Pull request by lennyluosz**
For Proposal issue#571

### CODE REVIEW

**Review by algobot76 — COMMENTED** [review]
I think `ifeq ... else ...endif` is redundant. Why not `[[ -e ${GOPATH|/bin/goimports]] || (echo "installing goimports ..."  && go install golang.org/x/tools/cmd/goimports@latest)`? This looks more idiomatic :)

**Comment by daniel-hutao** [comment]
Thanks for the pr @lennyluosz. I did some test locally and it seems that it still download `goimports` every time when I use `make build`

image

**Comment by daniel-hutao** [comment]
A gentle reminder: please pay attention to the conventional commit messages rules: https://www.conventionalcommits.org/en/v1.0.0/

We also have a link for it in our CONTRIBUTING.md.

**Comment by lennyluosz** [comment]
> 

Great. I will have a  try tomorrow

**Comment by lennyluosz** [comment]
thx for the guide.  I changed accordingly on both code & commit comments.     And it was weird that  it did not pass your test since it worked on  my Centos.  Anyway,  please kindly test again with updated code.

**Comment by daniel-hutao** [comment]
close #571

**Comment by daniel-hutao** [comment]
image

I've tested this pr and it does well.

@lennyluosz Thanks for the enhancement! Please stick some test snapshots next time.

@gb96 Thanks for your commit, but please don't commit to others pr directly. You can take a look at our issues list and choose an issue you are interested and leave some comments, then we'll claim that issue to you.

/cc @IronCore864

**Comment by gb96** [comment]
Strange github... I never touched this repo, much less committed anything. Not the first time a github commit has been incorrectly attributed to me.  Some kind of weird github bug!

**Pull request merged**
