### PR TITLE
feat: CoreConfig varFile and toolFile Relative Path Support

### PR DESCRIPTION
**Pull request by rxhuster**
## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](../CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [ ] I have added relevant tests

### CODE REVIEW

**Comment by daniel-hutao** [comment]
@rxhuster Good job!
Please contact me on WeChat and I will prepare a certificate and some gifts for you.

---

I've tested this pr locally. Everything does well.

---

close #660

**Review by daniel-hutao — APPROVED** [review]

**Comment by daniel-hutao** [comment]
I'd like to merge it now.

**Comment by summingyu** [comment]
You can look at this https://github.com/conventional-changelog/commitlint/#what-is-commitlint ,  welcome to the next pr

**Review by summingyu — COMMENTED** [review]
lgtm

**Pull request merged**
