### PR TITLE
fix: add token to avoid  github api rate limit

### PR DESCRIPTION
**Pull request by csonezp**
## Description

Add token to avoid  github api rate limit

## Related Issues
#955 

Signed-off-by: csonezp <csonezp@gmail.com>

### CODE REVIEW

**Comment by aFlyBird0** [comment]
Thank you for raising the issue and modifying the code yourself, and even modifying the documentation accordingly! @csonezp 🙌

The only thing worth discussing is that the new code forces users to set a GitHub token.

1. since quick start itself requires a GitHub token, it's perfectly fine to change it.
2. if the token is not empty, use the request with a header. Otherwise, try requesting without the request header, and if you get an error, prompt the user for the token.

Please [join CNCF's Slack](https://slack.cncf.io), and join our [channel in CNCF Slack](https://cloud-native.slack.com/messages/devstream)!
Here are a few useful things for you to continue your open-source journey:
- If you are searching for something else to work on, please see ["find an issue"](https://docs.devstream.io/en/latest/contributing_guide/#find-an-issue).
- Check out our [new contributor guide](https://docs.devstream.io/en/latest/contributing_guide/#new-contributor-guide) and the ["Developer Guide"](https://docs.devstream.io/en/latest/development/development-workflow/).
- Read our [blog](https://blog.devstream.io/); they are on [Medium](https://medium.com/devstream), too.

**Comment by csonezp** [comment]
> Thank you for raising the issue and modifying the code yourself, and even modifying the documentation accordingly! @csonezp 🙌
> 
> The only thing worth discussing is that the new code forces users to set a GitHub token.
> 
> 1. since quick start itself requires a GitHub token, we can leave it as is.
> 2. if the token is not empty, use the request with a header. Otherwise, try requesting without the request header, and if you get an error, prompt the user for the token.
> 
> cc @daniel-hutao @iyear @steinliber
> 
> Please [join CNCF's Slack](https://slack.cncf.io), and join our [channel in CNCF Slack](https://cloud-native.slack.com/messages/devstream)! Here are a few useful things for you to continue your open-source journey:
> 
> * If you are searching for something else to work on, please see ["find an issue"](https://docs.devstream.io/en/latest/contributing_guide/#find-an-issue).
> * Check out our [new contributor guide](https://docs.devstream.io/en/latest/contributing_guide/#new-contributor-guide) and the ["Developer Guide"](https://docs.devstream.io/en/latest/development/development-workflow/).
> * Read our [blog](https://blog.devstream.io/); they are on [Medium](https://medium.com/devstream), too.

Good idea, i modify the script to compatible with both cases

**Review by daniel-hutao — APPROVED** [review]
ltgm

I think it is ok, although the most of users will not set token in order to complete the download, but this code is better than nothing.

**Review by iyear — APPROVED** [review]
The modified code is robust and takes into different scenarios.

**Pull request merged**
