### PR TITLE
Docs: translate development-workflow into Chinese

### PR DESCRIPTION
**Pull request by DunyuSong**
## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md) documentation.
- [ ] My code has the necessary comments and documentation (if needed).
- [ ] I have added relevant tests

## Related Issues

#706

### CODE REVIEW

**Comment by IronCore864** [comment]
@DunyuSong A kind reminder that you haven't signed off on your commit(s) yet.

Check out our [official doc here](https://docs.devstream.io/en/latest/contributing_guide/#sign-your-commits) to learn how to do this.

Licensing is important to open source projects. It provides some assurances that the software will continue to be available based on the terms that the author(s) desired.

Now that we are part of CNCF, per CNCF's requirement, we kindly require that contributors sign off on commits submitted to our project's repositories. Thanks!

**Comment by DunyuSong** [comment]
I have executed "git commit --amend -s", how do I know if I have signed successfully?

**Comment by imxw** [comment]
> I have executed "git commit --amend -s", how do I know if I have signed successfully?

`git log -n1`

**Comment by DunyuSong** [comment]
I have signed.

**Comment by imxw** [comment]
> I have executed "git commit --amend -s", how do I know if I have signed successfully?

after that, you need to execute  `git push -f origin translation_development_workflow_chinese`

**Comment by IronCore864** [comment]
@imxw please help the original contributor regarding signing the commit. Thanks! @daniel-hutao maybe we can demo this in the next community meeting.

**Review by IronCore864 — APPROVED** [review]

**Pull request merged**
