### PR TITLE
Feat: Auto-Release Script Improvement

### PR DESCRIPTION
**Pull request by yclchuxue**
## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [ ] I have read through the [CONTRIBUTING.md](../CONTRIBUTING.md) documentation.
- [ ] My code has the necessary comments and documentation (if needed).
- [ ] I have added relevant tests

## Description

When a new version is released, the following methods can be used
```
sh xxx.sh tag=v0.5.0
```
## Related Issues

There will be a problem if more than one parameter is passed to the auto-release-darwin-arm64.sh file, and the first one is not tag=vx.x.x.
## New Behavior (screenshots if needed)

```
if [ $# -eq 1 ]
then
  info=$1
  tag=${info:4}
fi
```

### CODE REVIEW

**Comment by summingyu** [comment]
Would it be better to use "getops"?@yclchuxue

**Comment by yclchuxue** [comment]
Doesn't this require the input of parameters like "tag=v0.x.0"? If it is changed to "-t v0.x.0", it may not meet the requirements.Although I also feel it would be better to use getops.

**Comment by yclchuxue** [comment]
@summingyu

**Comment by daniel-hutao** [comment]
## Related Issues

close #505

**Comment by summingyu** [comment]
Sorry, I checked the documentation, "getopts" does not support "long options", "getopt" support "long options" @yclchuxue

**Comment by yclchuxue** [comment]
Ok,thanks.

**Pull request closed without merging**
