### PR TITLE
A better way to execute commands in Framework.

### PR DESCRIPTION
**Pull request by Esonhugh**
## Pre-Checklist

Note: please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](../CONTRIBUTING.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [x] I have added relevant tests

## Description
a fix to issue #583
Do some check before executed and provide a fix and add document for it.  

## Related Issues
#583 

## New Behavior (screenshots if needed)
```
=== RUN   TestExecInSystem
Shell Command: echo This Normal;cat /etc/passwd;echo This is accident.
Stdout: This Normal
Stdout: root:x:0:0:root:/root:/bin/zsh
Stdout: daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
....
Stderr: Stdout: This is accident.
Stdout: Exec: ls
Params : -al . ;cat /etc/passwd;echo This is accident.
Stderr: ls: 无法访问 ';cat /etc/passwd;echo This is accident.': 没有那个文件或目录
Stdout: .:
Stdout: 总用量 16
Stdout: drwxr-xr-x  3 kali kali 4096 May 23 12:19 .
Stdout: drwxr-xr-x 13 kali kali 4096 May 23 12:09 ..
Stdout: drwxr-xr-x  3 kali kali 4096 May 22 22:30 e2e
Stdout: -rw-r--r--  1 kali kali 1047 May 23 12:19 evil_test.go
Stdout: Stderr: Exec: echo bad Commands;cat /etc/passwd
Params : 
Stdout: Exec: sh
Params : -c ;cat /etc/passwd;echo This is accident.
Exec: kubectl
Params : --help
Stderr: Stdout: kubectl controls the Kubernetes cluster manager.
Stdout: 
Stdout:  Find more information at: https://kubernetes.io/docs/reference/kubectl/overview/
Stdout: 
Stdout: Basic Commands (Beginner):
Stdout:   create        Create a resource from a file or from stdin.
Stdout:   expose        Take a replication controller, service, deployment or pod and expose it as a new Kubernetes Service
Stdout:   run           Run a particular image on the cluster
Stdout:   set           Set specific features on objects
Stdout: 
Stdout: Basic Commands (Intermediate):
Stdout:   explain       Documentation of resources
Stdout:   get           Display one or many resources
Stdout:   edit          Edit a resource on the server
Stdout:   delete        Delete resources by filenames, stdin, resources and names, or by resources and label selector
Stdout: 
Stdout: Deploy Commands:
Stdout:   rollout       Manage the rollout of a resource
Stdout:   scale         Set a new size for a Deployment, ReplicaSet or Replication Controller
Stdout:   autoscale     Auto-scale a Deployment, ReplicaSet, or ReplicationController
Stdout: 
Stdout: Cluster Management Commands:
Stdout:   certificate   Modify certificate resources.
Stdout:   cluster-info  Display cluster info
Stdout:   top           Display Resource (CPU/Memory/Storage) usage.
Stdout:   cordon        Mark node as unschedulable
Stdout:   uncordon      Mark node as schedulable
Stdout:   drain         Drain node in preparation for maintenance
Stdout:   taint         Update the taints on one or more nodes
Stdout: 
Stdout: Troubleshooting and Debugging Commands:
Stdout:   describe      Show details of a specific resource or group of resources
Stdout:   logs          Print the logs for a container in a pod
Stdout:   attach        Attach to a running container
Stdout:   exec          Execute a command in a container
Stdout:   port-forward  Forward one or more local ports to a pod
Stdout:   proxy         Run a proxy to the Kubernetes API server
Stdout:   cp            Copy files and directories to and from containers.
Stdout:   auth          Inspect authorization
Stdout:   debug         Create debugging sessions for troubleshooting workloads and nodes
Stdout: 
Stdout: Advanced Commands:
Stdout:   diff          Diff live version against would-be applied version
Stdout:   apply         Apply a configuration to a resource by filename or stdin
Stdout:   patch         Update field(s) of a resource
Stdout:   replace       Replace a resource by filename or stdin
Stdout:   wait          Experimental: Wait for a specific condition on one or many resources.
Stdout:   kustomize     Build a kustomization target from a directory or a remote url.
Stdout: 
Stdout: Settings Commands:
Stdout:   label         Update the labels on a resource
Stdout:   annotate      Update the annotations on a resource
Stdout:   completion    Output shell completion code for the specified shell (bash or zsh)
Stdout: 
Stdout: Other Commands:
Stdout:   api-resources Print the supported API resources on the server
Stdout:   api-versions  Print the supported API versions on the server, in the form of "group/version"
Stdout:   config        Modify kubeconfig files
Stdout:   plugin        Provides utilities for interacting with plugins.
Stdout:   version       Print the client and server version information
Stdout: 
Stdout: Usage:
Stdout:   kubectl [flags] [options]
Stdout: 
Stdout: Use "kubectl <command> --help" for more information about a given command.
Stdout: Use "kubectl options" for a list of global command-line options (applies to all commands).
Stderr: Stdout: --- PASS: TestExecInSystem (0.09s)
PASS
```

### CODE REVIEW

**Comment by Esonhugh** [comment]
So tricky it is.

**Comment by IronCore864** [comment]
Please hold till discussion [here](https://github.com/devstream-io/devstream/issues/583) is resolved.

**Comment by IronCore864** [comment]
Closing now, see discussions here for more info:
https://github.com/devstream-io/devstream/issues/583

**Comment by IronCore864** [comment]
See PR https://github.com/devstream-io/devstream/pull/631 which deleted the dead code.

**Pull request closed without merging**
